import {expect,it} from 'vitest';import {readFileSync} from 'node:fs';import {Mesh} from 'three';import {applyAssemblyComponentPatch,fingerprintAssemblyIR} from '../src/engine/assembly-edit';import {compileAssemblyIR,validateAssemblyIR} from '../src/engine/assembly-compiler';import type {AssemblyIR} from '../src/engine/assembly-ir';
const source=(id='default'):AssemblyIR=>JSON.parse(readFileSync(`benchmarks/modeling-slices-20261004/assembly-lathe-normals/verified/${id}-after.json`,'utf8'));
const request=async(ir:AssemblyIR,segments:number)=>({schema:'morphloom.component-patch/0.2' as const,operationId:'lathe-segment-edit',componentId:'bushing',expectedInputFingerprint:await fingerprintAssemblyIR(ir),geometry:{operation:'lathe-segments',schema:'morphloom.lathe-segments/0.1',segments} as never});
function chord(g:Mesh['geometry'],radius:number){const p=g.getAttribute('position'),points=new Map<number,number[]>();for(let i=0;i<p.count;i++){const x=p.getX(i)*1000,z=p.getZ(i)*1000;if(Math.abs(Math.hypot(x,z)-radius)<radius*1e-5)points.set(Math.atan2(z,x),[x,z])}const ring=[...points].sort((a,b)=>a[0]-b[0]);return Math.max(...ring.map((a,i)=>{const b=ring[(i+1)%ring.length];return radius-Math.hypot((a[1][0]+b[1][0])/2,(a[1][1]+b[1][1])/2)}))}
function dispose(root:Mesh['parent']){root?.traverse(o=>{if(o instanceof Mesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose()}})}
it('edits existing segments and reduces actual chord error while preserving bounds and non-target buffers',async()=>{
 for(const [id,segments] of [['small',36],['default',48],['large',144],['solid',96]] as const){const ir=source(id),original=structuredClone(ir),next=await applyAssemblyComponentPatch(ir,await request(ir,segments));expect(ir).toEqual(original);expect(next.ir.components[1]).toEqual(ir.components[1]);expect(next.receipt.unaffectedComponentsPreserved).toBe(true);const a=compileAssemblyIR(ir,'beauty'),b=compileAssemblyIR(next.ir,'beauty');try{const old=a.root.getObjectByName('bushing') as Mesh,edited=b.root.getObjectByName('bushing') as Mesh,radius=id==='small'?7:id==='large'?28:14;expect(chord(edited.geometry,radius)).toBeLessThanOrEqual(.03);expect(chord(edited.geometry,radius)).toBeLessThan(chord(old.geometry,radius));old.geometry.computeBoundingBox();edited.geometry.computeBoundingBox();expect(edited.geometry.boundingBox).toEqual(old.geometry.boundingBox);const x=a.root.getObjectByName('preserved') as Mesh,y=b.root.getObjectByName('preserved') as Mesh;for(const key of ['position','normal','uv'])expect(y.geometry.getAttribute(key).array).toEqual(x.geometry.getAttribute(key).array);expect(y.geometry.index?.array).toEqual(x.geometry.index?.array);expect(b.metrics.topology.pass).toBe(true);}finally{dispose(a.root);dispose(b.root)}}
});
it('saves/reopens declarative IR and repeated absolute edits never accumulate or rewrite other fields',async()=>{const ir=source(),next=(await applyAssemblyComponentPatch(ir,await request(ir,48))).ir;const reopened=JSON.parse(JSON.stringify(next));validateAssemblyIR(reopened);expect(reopened).toEqual(next);await expect(applyAssemblyComponentPatch(reopened,await request(reopened,48))).rejects.toThrow(/isolated edit/);expect(reopened).toEqual(next);const step=(await applyAssemblyComponentPatch(reopened,await request(reopened,64))).ir;expect((await applyAssemblyComponentPatch(step,await request(step,48))).ir).toEqual(next);const expected=structuredClone(ir);if(expected.components[0].geometry.op!=='lathe')throw Error();expected.components[0].geometry.segments=48;expect(next).toEqual(expected);await expect(applyAssemblyComponentPatch(next,await request(ir,64))).rejects.toThrow(/stale/)});
it('blocks unsafe commands, older versions, wrong targets and mapping/frozen-contract inputs without mutation',async()=>{
 const ir=source(),snapshot=structuredClone(ir),base=await request(ir,48);
 for(const geometry of [{...base.geometry as object,segments:32.5},{...base.geometry as object,segments:0},{...base.geometry as object,segments:513},{...base.geometry as object,schema:'future'},{...base.geometry as object,extra:true}])await expect(applyAssemblyComponentPatch(ir,{...base,geometry:geometry as never})).rejects.toThrow();
 await expect(applyAssemblyComponentPatch(ir,{...base,schema:'morphloom.component-patch/0.1'})).rejects.toThrow(/0.2/);
 await expect(applyAssemblyComponentPatch(ir,{...base,componentId:'preserved'})).rejects.toThrow(/lathe/);
 const projected=source();projected.components[0].material.surface='brushed-metal';await expect(applyAssemblyComponentPatch(projected,await request(projected,48))).rejects.toThrow(/mapping/);
 const locked={...source(),fidelity:{} as never};await expect(applyAssemblyComponentPatch(locked,await request(locked,48))).rejects.toThrow(/frozen/);
 expect(ir).toEqual(snapshot);
});
it('rejects budget overflow and later unsupported batch edits atomically',async()=>{
 const {applyAssemblyComponentBatchPatch}=await import('../src/engine/assembly-edit');const ir=source(),snapshot=structuredClone(ir);
 await expect(applyAssemblyComponentBatchPatch(ir,{schema:'morphloom.component-batch-patch/0.2',operationId:'atomic',expectedInputFingerprint:await fingerprintAssemblyIR(ir),edits:[{componentId:'bushing',geometry:(await request(ir,48)).geometry},{componentId:'preserved',geometry:(await request(ir,48)).geometry}]})).rejects.toThrow(/lathe/);expect(ir).toEqual(snapshot);
 const large=source();if(large.components[0].geometry.op!=='lathe')throw Error();large.components[0].geometry.profile=Array.from({length:102},(_,i)=>[8+i*.1,i]);await expect(applyAssemblyComponentPatch(large,await request(large,512))).rejects.toThrow(/budget/);
});
