import {expect,it}from'vitest';
import {correctRequiredDeclaration}from'../src/engine/declaration-correction';
import {createElementDomainRegistry}from'../src/engine/element-domain-packs';
import {centeredPlatePack}from'../src/engine/centered-plate-pack';
const registry=createElementDomainRegistry();registry.register(centeredPlatePack);
const d={schema:'sceliph.domain-invocation/0.1',units:'mm',coordinates:'right-handed-y-up',packId:centeredPlatePack.metadata.id,input:{widthMm:37,heightMm:17,thicknessMm:2.5,boreDiameterMm:7},requiredCapabilities:['generate']},wrong={...d,input:{...d.input,widthMm:39}},r={schema:'sceliph.domain-requirements/0.1',units:'mm',coordinates:'right-handed-y-up',packId:d.packId,input:d.input};
const text=JSON.stringify(d),bad=JSON.stringify(wrong),requirements=JSON.stringify(r);
it('uses no inference for a matching declaration and at most one for a request mismatch',async()=>{let calls=0;const propose=async(feedback:any)=>{calls++;expect(feedback.reason).toContain('widthMm');expect(feedback.requirements).toBe(requirements);expect(feedback.maximumAttempts).toBe(1);return text;};expect((await correctRequiredDeclaration(registry,text,requirements,propose)).attempts).toBe(0);expect(calls).toBe(0);expect((await correctRequiredDeclaration(registry,bad,requirements,propose)).attempts).toBe(1);expect(calls).toBe(1);});
it('does not retry invalid source/contracts or publish a second invalid answer',async()=>{let calls=0;const propose=async()=>{calls++;return bad;};await expect(correctRequiredDeclaration(registry,'{}',requirements,propose)).rejects.toThrow();await expect(correctRequiredDeclaration(registry,bad,'{}',propose)).rejects.toThrow();expect(calls).toBe(0);await expect(correctRequiredDeclaration(registry,bad,requirements,propose)).rejects.toThrow('Request mismatch');expect(calls).toBe(1);});
it('rejects late answers after cancellation and retains the originally captured requirement values',async()=>{let alive=true,resolve!:(text:string)=>void;const response=new Promise<string>(r=>resolve=r),job=correctRequiredDeclaration(registry,bad,requirements,()=>response,()=>alive);alive=false;resolve(text);await expect(job).rejects.toThrow('cancelled');});

it('keeps UI feedback bound to the failed file and clears it on replacement or discard',async()=>{const {ElementSourceLoadSession}=await import('../src/element-source-load');const {parseEditableElementSource}=await import('../src/engine/editable-source');const session=new ElementSourceLoadSession();let published=0;const file=(v:string)=>({name:'decl.json',size:v.length,text:async()=>v});await session.load(file(bad),()=>true,()=>published++,()=>{},value=>parseEditableElementSource(registry,value,requirements));expect(session.state.status).toBe('failed');if(session.state.status!=='failed')throw Error('Expected failure');expect(session.state.correction?.declaration).toBe(bad);expect(session.state.correction?.requirements).toBe(requirements);expect(published).toBe(0);session.restore();expect(session.state).toEqual({status:'ready'});await session.load(file(text),()=>true,()=>published++,()=>{},value=>parseEditableElementSource(registry,value,requirements));expect(session.state).toEqual({status:'ready'});expect(published).toBe(1);});
it('does not publish a result when a provider cancels the captured generation intent',async()=>{let alive=true;const r=createElementDomainRegistry();r.register({...centeredPlatePack,generate:input=>{alive=false;return centeredPlatePack.generate(input);}});await expect(correctRequiredDeclaration(r,text,requirements,async()=>text,()=>alive)).rejects.toThrow('cancelled');});
