import {it,expect} from 'vitest';import {generateSpurGearProject} from '../src/engine/gear-pack';import {migrateElementProjectToV4,editPart} from '../src/engine/element-project';import {exportSelectedScene} from '../src/engine/element-renderer';import {inspectUvQuality} from '../src/engine/uv-quality';import {evaluateMeshUvExport} from '../src/engine/mesh-export-policy';
it('blocks actual default gear UV failure and distinguishes diagnostic purpose',async()=>{const p=generateSpurGearProject({}),s=exportSelectedScene(p,[p.parts[0].id]);try{const report=await inspectUvQuality(s.root);expect(report.integrityPass).toBe(false);expect(evaluateMeshUvExport(report,'editable-mesh').allowed).toBe(false);const diagnostic=evaluateMeshUvExport(report,'diagnostic');expect(diagnostic.allowed).toBe(true);expect(diagnostic.issues.some(i=>i.id===p.parts[0].id)).toBe(true);expect(diagnostic.productionApproved).toBe(false);}finally{s.dispose();}});
it('allows actual repaired UV without claiming production approval',async()=>{const p=migrateElementProjectToV4(generateSpurGearProject({})),q=editPart(p,p.parts[0].id,{uvScale:100}),s=exportSelectedScene(q,[q.parts[0].id]);try{const decision=evaluateMeshUvExport(await inspectUvQuality(s.root),'editable-mesh');expect(decision.allowed).toBe(true);expect(decision.productionApproved).toBe(false);}finally{s.dispose();}});
it('checks actual GLB bytes and records failed diagnostic UV without production approval',async()=>{const {vi}=await import('vitest'),{GLTFExporter}=await import('three/addons/exporters/GLTFExporter.js'),{inspectMeshExport}=await import('../src/engine/mesh-export-policy');class Reader{result:ArrayBuffer|null=null;onloadend:(()=>void)|null=null;readAsArrayBuffer(b:Blob){void b.arrayBuffer().then(v=>{this.result=v;this.onloadend?.();});}}vi.stubGlobal('FileReader',Reader);const p=generateSpurGearProject({}),s=exportSelectedScene(p,[p.parts[0].id]);try{const bytes=await new GLTFExporter().parseAsync(s.root,{binary:true}) as ArrayBuffer;await expect(inspectMeshExport(bytes,JSON.stringify(p),'editable-mesh')).rejects.toThrow(/spur_gear/);const receipt=await inspectMeshExport(bytes,JSON.stringify(p),'diagnostic');expect(receipt.meshExport.uv.allowed).toBe(true);expect(receipt.meshExport.uv.productionApproved).toBe(false);expect(receipt.report.integrityPass).toBe(false);expect(receipt.meshExport.standard.errors).toBe(0);}finally{s.dispose();vi.unstubAllGlobals();}});
it('blocks one damaged connected feature even while aggregate UV stays under five percent',async()=>{const p=migrateElementProjectToV4(generateSpurGearProject({})),q=editPart(p,p.parts[0].id,{uvScale:100}),s=exportSelectedScene(q,[q.parts[0].id]);try{const before=await inspectUvQuality(s.root,{includeTriangles:true}),mesh=s.root.getObjectByName(q.parts[0].id) as import('three').Mesh,rows=before.meshes[0].triangles!.filter(t=>t.connectedFeatureId?.endsWith('/tooth_0003')&&!t.legacyDegenerate).slice(0,Math.floor(before.meshes[0].features.find(f=>f.id.endsWith('/tooth_0003'))!.triangles*.05)+1);expect(rows.length).toBeGreaterThan(12);for(const t of rows)for(let k=0;k<3;k++)mesh.geometry.getAttribute('uv').setXY(t.index*3+k,0,0);const report=await inspectUvQuality(s.root),m=report.meshes[0];expect(m.degenerateUvTriangles/m.eligibleUvTriangles).toBeLessThan(.05);const decision=evaluateMeshUvExport(report,'editable-mesh');expect(decision.allowed).toBe(false);expect(decision.issues.some(i=>i.id.endsWith('/tooth_0003'))).toBe(true);}finally{s.dispose();}});

it('explains actual small UVs separately from truly collapsed and non-finite UVs without changing export decisions',async()=>{
 const {UV_DOUBLE_AREA_EPSILON}=await import('../src/engine/uv-quality');
 const p=generateSpurGearProject({}),s=exportSelectedScene(p,[p.parts[0].id]);
 try{const report=await inspectUvQuality(s.root),m=report.meshes[0];expect(m.zeroUvTriangles).toBe(0);expect(m.degenerateUvTriangles).toBeGreaterThan(0);
 const decision=evaluateMeshUvExport(report,'editable-mesh');expect(decision.allowed).toBe(false);
 expect(decision.issues.find(i=>i.id===m.id)?.reason).toContain(`double-area <= ${UV_DOUBLE_AREA_EPSILON} or non-finite`);
 expect(decision.issues.find(i=>i.id===m.id)?.reason).toContain('0 exactly zero-area');
 const mesh=s.root.getObjectByName(m.id) as import('three').Mesh,uv=mesh.geometry.getAttribute('uv');
 for(let i=0;i<uv.count;i++)uv.setXY(i,0,0);
 const collapsed=await inspectUvQuality(s.root);expect(collapsed.meshes[0].zeroUvTriangles).toBe(collapsed.meshes[0].eligibleUvTriangles);expect(evaluateMeshUvExport(collapsed,'editable-mesh').allowed).toBe(false);
 expect(evaluateMeshUvExport(collapsed,'diagnostic').issues[0].reason).toContain(`${collapsed.meshes[0].zeroUvTriangles} exactly zero-area`);
 uv.setX(0,NaN);const invalid=await inspectUvQuality(s.root);expect(invalid.meshes[0].invalidUvVertices).toBeGreaterThan(0);expect(evaluateMeshUvExport(invalid,'editable-mesh').allowed).toBe(false);
 }finally{s.dispose();}
});
