import type {DomainPack} from './element-domain-packs';
import {validateProject,type ElementProject} from './element-project';
export const CENTERED_PLATE_REVISION='sceliph.centered-plate/0.1';
const defaults={widthMm:20,heightMm:10,thicknessMm:4,boreDiameterMm:4};
/** Explicit dimensions, not a recovered photograph or manufacturing solid. */
export function generateCenteredPlateProject(input:Readonly<Record<string,unknown>>):ElementProject{
 if(!input||typeof input!=='object'||Array.isArray(input)||![Object.prototype,null].includes(Object.getPrototypeOf(input))||Object.keys(input).some(k=>!['seed','units','coordinates',...Object.keys(defaults)].includes(k))||input.units!==undefined&&input.units!=='mm'||input.coordinates!==undefined&&input.coordinates!=='right-handed-y-up'||input.seed!==undefined&&(!Number.isSafeInteger(input.seed)||(input.seed as number)<0))throw Error('Invalid centered plate input/frame.');
 const values=Object.fromEntries(Object.entries(defaults).map(([k,v])=>[k,Object.hasOwn(input,k)?input[k]:v]))as typeof defaults;
 const {widthMm:w,heightMm:h,thicknessMm:t,boreDiameterMm:b}=values;
 if(Object.values(values).some(v=>typeof v!=='number'||!Number.isFinite(v))||w<.1||h<.1||w>1000||h>1000||t<.01||t>1000||b<0||b>100||b>=Math.min(w,h)-.02)throw Error('Invalid plate dimensions/wall clearance.');
 const holes=b===0?undefined:[Array.from({length:128},(_,i)=>{const a=-2*Math.PI*i/128;return [b/2*Math.cos(a),b/2*Math.sin(a)]as[number,number];})];
 return validateProject({schema:'morphloom.elements/0.6',seed:input.seed??42,units:'mm',coordinates:'right-handed-y-up',parts:[{id:'plate_body',name:'Centered plate with declared through bore',position:[0,0,0],rotation:[0,0,0],scale:[1,1,1],shape:'assembly-geometry',geometry:{op:'extrude',points:[[-w/2,-h/2],[w/2,-h/2],[w/2,h/2],[-w/2,h/2]],depth:t,...(holes?{holes}:{})},color:'#90949a',material:{roughness:.68,metalness:0},evidence:{status:'authored',source:CENTERED_PLATE_REVISION+'; declared dimensions, polygonal bore; not CAD/BREP/tolerance approval'},visible:true,locked:false}],regions:[],groups:[],elements:[]});
}
export const centeredPlatePack:DomainPack={metadata:{version:'morphloom.domain-pack/0.4',id:'product.centered-plate',domain:'product-visualization',status:'experimental',capabilities:['generate','semantic-part-editing','selected-scene-export','authored-single-extrusion'],representation:{id:'morphloom.elements/0.6',mode:'native'},units:'mm',coordinates:'right-handed-y-up',parameters:{seed:'uint-safe-integer',dimensions:{widthMm:{min:.1,max:1000,default:20},heightMm:{min:.1,max:1000,default:10},thicknessMm:{min:.01,max:1000,default:4},boreDiameterMm:{min:0,max:100,default:4}}},parameterNotes:['XYZ centered by the existing renderer; Z spans ±thicknessMm/2. All dimensions in millimeters.','Bore is actual128-segment polygonal geometry; remaining wall clearance must exceed0.02mm.','Authored product visualization, not manufacturer geometry or CAD/BREP approval.'],constraints:{maxElements:5000},operations:['generate'],tools:['generic-inspector'],evidencePaths:['parts.*.evidence'],exportAdapters:[{id:'source-json',editing:'full'},{id:'baked-glb',editing:'baked-only'}],dependencies:{engineApi:'0.4'}},generate:generateCenteredPlateProject};
